import {
  Bike,
  Bone,
  BookHeart,
  BookMarked,
  BookOpen,
  Braces,
  Brush,
  Cat,
  Clapperboard,
  Code,
  CodeXml,
  Dumbbell,
  FileScan,
  Fish,
  FolderKanban,
  Goal,
  GraduationCap,
  HandHeart,
  Image,
  LampDesk,
  LandPlot,
  Languages,
  MessageCircleMore,
  Microscope,
  NotebookPen,
  NotepadText,
  PawPrint,
  PenTool,
  PencilRuler,
  Pill,
  PillBottle,
  Plane,
  ScanSearch,
  School,
  ShieldPlus,
  ShoppingBasket,
  ShoppingCart,
  Sigma,
  Tag,
  TentTree,
  Terminal,
  TextSearch,
  User,
} from 'lucide-react';

export const AttributeIcon = {
  'land-plot': LandPlot,
  tag: Tag,
  goal: Goal,
  'book-heart': BookHeart,
  'folder-kanban': FolderKanban,
  'message-circle-more': MessageCircleMore,
  'hand-heart': HandHeart,
  'lamp-desk': LampDesk,
  dumbbell: Dumbbell,
  'notebook-pen': NotebookPen,
  'book-open': BookOpen,
  'book-marked': BookMarked,
  clapperboard: Clapperboard,
  images: Image,
  bike: Bike,
  plane: Plane,
  'tent-tree': TentTree,
  'graduation-cap': GraduationCap,
  languages: Languages,
  sigma: Sigma,
  code: Code,
  'file-scan': FileScan,
  braces: Braces,
  terminal: Terminal,
  'code-xml': CodeXml,
  user: User,
  cat: Cat,
  fish: Fish,
  bone: Bone,
  'paw-print': PawPrint,
  'shield-plus': ShieldPlus,
  'pill-bottle': PillBottle,
  pill: Pill,
  microscope: Microscope,
  'notepad-text': NotepadText,
  school: School,
  'scan-search': ScanSearch,
  'text-search': TextSearch,
  'shopping-cart': ShoppingCart,
  'shopping-basket': ShoppingBasket,
  brush: Brush,
  'pen-tool': PenTool,
  'pencil-ruler': PencilRuler,
};
